name: tide_kit
description: "A toolkit for building IDE and studio like apps."
version: 1.0.0
repository: https://github.com/larryaasen/tide

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  get_it: ^8.0.2
  upgrader: ^11.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
