name: Take Screenshot

defaults:
  run:
    working-directory: packages/tide

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  take_screenshot:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PowerShell script to take screenshot
        run: |
          pwd;
          ls;
          ls scripts;
          # git-bash.exe -c "pwd";
          # git-bash.exe -c "ls -al";
          # git-bash.exe -c "ls -al scripts";
          powershell.exe -File scripts/take_screenshot_windows.ps1;

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png
