name: Flutter Unit Tests

defaults:
  run:
    working-directory: packages/tide

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        flutter-version: ['3.24.0', '3.24.5']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter ${{ matrix.flutter-version }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter-version }}'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run unit and widget tests
        run: flutter test --coverage --coverage-path=lcov.info
